### ISSUE TITLE
sustainability modules: final updates to IDS elements

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#473]
There are some final updates to be made to a deadline, primarily to the IDS Sustainability modules following feedback from the World Bank. This issue is to collect them all in one place:

- [x] update mapping for Cost Benefit Analysis https://github.com/open-contracting/infrastructure/issues/472
- [x] add new documentType code https://github.com/open-contracting/infrastructure/issues/470
- [x] Update titles and descriptions in `sustainability.yaml` with the final versions from the [CoST IDS sustainability elements spreadsheet](https://docs.google.com/spreadsheets/d/165epI69oQ5YyL4-2q8VubFn9VuNham2Pi1u0P49id9o/edit#gid=0)
- [x] Final copy-edit of mapping and examples in `sustainability.yaml`
- [x] Resolve any outstanding issues reported by `./manage.py lint`
- [x] Check the built version of `schema.md` and update `:collapse:` option of jsonschema directives as needed (probably just for the project table).
- [x] add new codes to conservationMeasure https://github.com/open-contracting/infrastructure/issues/474
